Fix/complete not implemented workout comments and some fixes
EndurAi/EndurAi pull request #186
Opened 2024-12-16 21:38 UTC by Shayan105

# Summary :
This PR complete some non implemented case of the coach feedback such as the Warrior II exercise and the Jumping jacks exercise. 
## Make the Coach feedback feature more explicit 
The PR  also makes the coach feed back anouncement more explicit by simply adding a "Click on me !" when the coach asks the user if he wants to get feedback. This issue was pointed out during a test made by a random user. 
## New data structure for the coach feedback
Some exercises ,such as the jumping jacks, does not require any feedback but only counting repetition.These case are handled by the updated architecture of the CoachFeedback class. 

## Give feedback on the multiple part of the exercise 
Feedback was previously given as a whole to the user. While this is fine with exercise with only one position, this becomes problematic when it comes to exercises with multiple position to analyse such as the two poses of the push-up (low and high).
The new architecture allows the user to get Feedback on both parts.

2024-12-17 22:02 UTC, Siupahc requested changes
Good fixes, maybe there is a typo you should check

2024-12-18 11:46 UTC, Shayan105 commented on app/src/main/java/com/android/sample/mlUtils/exercisesCriterions/DownwardDogCriterions.kt
> +        criterionName = ExerciseType.DOWNWARD_DOG.toString(),
The exercise name is simply the name of the exercise being done. Whereas the citerion name is the of the assessed criterion. This becomes handy when you have exercises that are made of 2 criterion ex : push  up low and push up high. 
The feedback explicit wich phase of the exercise need advice. Here is an example :
Well done, here are some advice for improvement:
Push ups low position : Keep your bag right

2024-12-18 12:35 UTC, Siupahc commented on app/src/main/java/com/android/sample/mlUtils/exercisesCriterions/DownwardDogCriterions.kt
> +        criterionName = ExerciseType.DOWNWARD_DOG.toString(),
Oh I see, maybe we could have used a default value for the criterionName which is exerciseName if not provided. But this is fine

2024-12-18 12:40 UTC, Siupahc approved these changes
Changes have been taken into account

2024-12-18 12:40 UTC, Siupahc commented on app/src/main/java/com/android/sample/mlUtils/ExerciseFeedBack.kt
> +      val mult = 2f
Good use of a constant, maybe we could name it in uppercase since it's the convention, but I don't think we did it for this project, so this is fine

2024-12-18 19:44 UTC, merged